.PHONY: all clean act friends http miiverse ssl socket nim mint

all: act friends http miiverse ssl socket nim mint

act:
	@make -C act

friends:
	@make -C friends

http:
	@make -C http

miiverse:
	@make -C miiverse

ssl:
	@make -C ssl

socket:
	@make -C socket

nim:
	@make -C nim

mint:
	@make -C mint

clean:
	@make -C act clean
	@make -C friends clean
	@make -C http clean
	@make -C miiverse clean
	@make -C ssl clean
	@make -C socket clean
	@make -C nim clean
	@make -C mint clean
